"""
    Robert Koch Institut: Corona Risikogebiete API

    Aktuelle Corona Risikogebietsinformationen als API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.risikogebiete.model.risk_countries import RiskCountries

from deutschland import risikogebiete


class TestRiskCountries(unittest.TestCase):
    """RiskCountries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskCountries(self):
        """Test RiskCountries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskCountries()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
